---
kind: pipeline
name: go-1-18

steps:
- name: test
  image: golang:1.18
  commands:
  - go test ./...
  - go build -v ./cmd/localrelay

---
kind: pipeline
name: go-1-19

steps:
- name: test
  image: golang:1.19
  commands:
  - go test ./...
  - go build -v ./cmd/localrelay

---
kind: pipeline
name: go-1-17

steps:
- name: test
  image: golang:1.17
  commands:
  - go test ./...
  - go build -v ./cmd/localrelay