---
kind: pipeline
type: docker
name: go-1-18

steps:
  - name: test
    image: golang:1.18
    commands:
      - go test ./...
      - go build -v ./cmd/localrelay

  - name: build-failed-notification
    image: curlimages/curl:8.00.1
    environment:
      notify:
        from_secret: notification_webhook
    when:
      status:
        - failure
    commands:
      - "curl -v $notify -F 'title=Build Failed: ${DRONE_REPO}' -F $'message=[Build Failed] ${DRONE_REPO}\n[COMMIT] ${DRONE_COMMIT}\n[BRANCH] ${DRONE_BRANCH}\n'"

---
kind: pipeline
type: docker
name: go-1-19

steps:
  - name: test
    image: golang:1.19
    commands:
      - go test ./...
      - go build -v ./cmd/localrelay

  - name: build-failed-notification
    image: curlimages/curl:8.00.1
    environment:
      notify:
        from_secret: notification_webhook
    when:
      status:
        - failure
    commands:
      - "curl -v $notify -F 'title=Build Failed: ${DRONE_REPO}' -F $'message=[Build Failed] ${DRONE_REPO}\n[COMMIT] ${DRONE_COMMIT}\n[BRANCH] ${DRONE_BRANCH}\n'"

---
kind: pipeline
type: docker
name: go-1-17

steps:
  - name: test
    image: golang:1.17
    commands:
      - go test ./...
      - go build -v ./cmd/localrelay

  - name: build-failed-notification
    image: curlimages/curl:8.00.1
    environment:
      notify:
        from_secret: notification_webhook
    when:
      status:
        - failure
    commands:
      - "curl -v $notify -F 'title=Build Failed: ${DRONE_REPO}' -F $'message=[Build Failed] ${DRONE_REPO}\n[COMMIT] ${DRONE_COMMIT}\n[BRANCH] ${DRONE_BRANCH}\n'"

---
kind: pipeline
type: docker
name: osv-dependency-scan

steps:
  - name: osv-vuln-dep-scanner
    image: golang
    commands:
      - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - osv-scanner -r ./
  - name: build-failed-notification
    image: curlimages/curl:8.00.1
    environment:
      notify:
        from_secret: notification_webhook
    when:
      status:
        - failure
    commands:
      - "curl -v $notify -F 'title=Vulnerability In ${DRONE_REPO}' -F $'message=[Build Failed] ${DRONE_REPO}\n[COMMIT] ${DRONE_COMMIT}\n[BRANCH] ${DRONE_BRANCH}'"
